services:
  - type: web
    name: digital
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /DemoBuild/*.br
        name: Content-Encoding
        value: br
      - path: /DemoBuild/*.br
        name: Content-Type
        value: application/octet-stream
